name: IsletopiaTweakers
version: ${project.version}
main: com.molean.isletopia.tweakers.IsletopiaTweakers
api-version: 1.13
softdepend:
  - PlaceholderAPI
denpend:
  - PlotSquared
  - AdvancedCommand
  - SkinsRestorer
  - AuthMe
commands:
  guide: {}
  help: {}
  visit: {}
  issue: {}
  sudo: {}
  parameter: {}
  otherparameter: {}