name: IsletopiaTweakers
version: 1.0-SNAPSHOT
main: com.molean.isletopia.IsletopiaTweakers
api-version: 1.13
load: STARTUP
denpend:
  - PlotSquared
commands:
  cmd: { }
  isadmin:
    aliases:
      - isa
      - isadmin
      - islandadmin
    permission: isletopia.admin
  mail: { }
  inbox: { }
  isdebug:
    permission: isletopia.isdebug
  clubrealm: { }
  slime: { }
  transform:
    permission: isletopia.transform
  getup: { }
  firework:
    permission: isletopia.firework
  gtp:
    permission: isletopia.gtp
  gsend:
    permission: isletopia.gsend
  gcmd:
    permission: isletopia.gcmd
  parameter:
    permission: isletopia.parameter
  guide: { }
  help: { }
  visit: { }
  issue: { }
  menu: { }
  tell:
    aliases:
      - msg
      - w
  island:
    aliases:
      - is
      - islet
      - isletopia
  staticmap: { }
  mobcap: { }
  backup: { }
  download: { }
  bumpreward: { }
  likereward: { }
  luckycolor: { }
  clock: { }
  powerbar: { }
  waterbar: { }
  productionbar: { }
  reloadpermission:
    permission: isletopia.admin
  skiptutor: { }
  claim: { }
  entitybar: { }
  sleep: { }
  goodnight: { }
  music: { }
  blueprint: { }

