name: IsletopiaTweakers
version: ${project.version}
main: com.molean.isletopia.tweakers.IsletopiaTweakers
api-version: 1.13
softdepend:
  - PlaceholderAPI
denpend:
  - PlotSquared
commands:
  guide: {}
  help: {}
  visit: {}
  issue: {}
  sudo: {}
  parameter: {}
  parameterAdmin: {}
  tell: {}
  msg: {}