name: IsletopiaTweakers
version: 1.0-SNAPSHOT
main: com.molean.isletopia.IsletopiaTweakers
api-version: 1.13
softdepend:
  - PlaceholderAPI
denpend:
  - PlotSquared
commands:
  guide: {}
  help: {}
  visit: {}
  issue: {}
  sudo: {}
  parameter: {}
  parameterAdmin: {}
  tell: {}
  msg: {}
  w: {}
  is: {}
  island: {}
  islet: {}
  isletopia: {}