name: IsletopiaTweakers
version: 1.0-SNAPSHOT
main: com.molean.isletopia.IsletopiaTweakers
api-version: 1.13
denpend:
  - PlotSquared
commands:
  isdebug:
    permission: isletopia.isdebug
  clubrealm: { }
  transform:
    permission: isletopia.transform
  getup: { }
  consume: { }
  firework:
    permission: isletopia.firework
  gtp:
    permission: isletopia.gtp
  gsend:
    permission: isletopia.gsend
  gcmd:
    permission: isletopia.gcmd
  parameter:
    permission: isletopia.parameter
  guide: { }
  help: { }
  visit: { }
  issue: { }
  menu: { }
  tell: { }
  msg: { }
  w: { }
  is: { }
  island: { }
  islet: { }
  isletopia: { }
  temp: { }
  staticmap: { }
  ignore: { }
  unignore: { }
  mobcap: { }
  backup: { }
  download: { }
  redstone: { }
  bumpreward: { }
  luckycolor: { }
  clock: { }
  test: { }
